/** @type {import('next').NextConfig} */

module.exports = {
  images: {
    domains: ["avatars.githubusercontent.com"],
  },
  transpilePackages: [
    "@ant-design/colors",
    "@ant-design/cssinjs",
    "@ant-design/cssinjs-utils",
    "@ant-design/fast-color",
    "@ant-design/icons",
    "@ant-design/icons-svg",
    "@ant-design/react-slick",
    "@babel/runtime",
    "@rc-component/color-picker",
    "@rc-component/mutate-observer",
    "@rc-component/qrcode",
    "@rc-component/tour",
    "@rc-component/trigger",
    "classnames",
    "copy-to-clipboard",
    "dayjs",
    "rc-cascader",
    "rc-checkbox",
    "rc-collapse",
    "rc-dialog",
    "rc-drawer",
    "rc-dropdown",
    "rc-field-form",
    "rc-image",
    "rc-input",
    "rc-input-number",
    "rc-mentions",
    "rc-menu",
    "rc-motion",
    "rc-notification",
    "rc-pagination",
    "rc-picker",
    "rc-progress",
    "rc-rate",
    "rc-resize-observer",
    "rc-segmented",
    "rc-select",
    "rc-slider",
    "rc-steps",
    "rc-switch",
    "rc-table",
    "rc-tabs",
    "rc-textarea",
    "rc-tooltip",
    "rc-tree",
    "rc-tree-select",
    "rc-upload",
    "rc-util",
    "scroll-into-view-if-needed",
    "throttle-debounce",
  ],
  reactStrictMode: true,
};
